{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bottlerocket-updater.fullname" . }}
  labels:
    {{- include "bottlerocket-updater.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["pods/eviction"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bottlerocket-updater.fullname" . }}
  labels:
    {{- include "bottlerocket-updater.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bottlerocket-updater.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bottlerocket-updater.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
